/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package venta;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;


/**
 *
 * @author Didier Recalde 
 */
public class Camion extends javax.swing.JFrame {
    
    ResultSet resultado;
    Controlador controlador;
    
    String objeto = "buses";
    String id = "id";
    String cadenaSQL = null;
    boolean editar = false;
    int estado = 0;
    int gencod = 0;
    java.util.Date fechaActual;
    SimpleDateFormat formatoFECHA;
    private Statement sentencia;

    /**
     * Creates new form Camion
     */
    public Camion() {
        initComponents();
        setTitle("Formulario de buses");
        setLocationRelativeTo(null);
        controlador = new Controlador();
        
        fechaActual = new java.util.Date();
        formatoFECHA = new SimpleDateFormat("dd/MM/yyyy");
        inicializar();
        recuperarBuses();
    }  
   
    
    
    
    void limpiar(){
        txtchapa.setText("");
        txtaño.setText("");
        txtmarca.setText("");
        txtasi.setText("");
        
    }
    public void inicializar() {
        gencod = controlador.generarCodigo(objeto, id);
        txtid.setText(String.valueOf(gencod));
        
        txtchapa.setText("0");
        txtaño.setText("1");
        txtmarca.setText("0");
        txtasi.setText("");
        recuperarBuses();
    }
    void bloquear(){
        txtchapa.setEnabled(false);
        txtaño.setEnabled(false);
        txtmarca.setEnabled(false);
        

        btnnuevo.setEnabled(true);
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);        
    }
    
    void habilitar(){
        txtchapa.setEnabled(true);
        txtaño.setEnabled(true);
        txtmarca.setEnabled(true);
        
      
        btnnuevo.setEnabled(false);
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);        
    }
    
    void actualizar(){
        txtchapa.setEnabled(true);
        txtaño.setEnabled(true);
        txtmarca.setEnabled(true);
        
      
        btnactualizar.setEnabled(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtchapa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluses = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        btnmostrar = new javax.swing.JButton();
        txtmarca = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camion");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Chapa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        getContentPane().add(txtchapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 102, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Año: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        getContentPane().add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 123, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 83, -1));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 83, -1));

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 83, -1));

        btnmenu.setText("RMenu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 83, -1));

        tbluses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Año", "Chapa", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbluses.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbluses);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 571, 116));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Buscar: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
        });
        getContentPane().add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 142, -1));

        btnmostrar.setText("Mostrar Todos");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 121, -1));

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtid.setEnabled(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 130, 120, -1));

        jLabel8.setFont(new java.awt.Font("Linux Libertine G", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buses");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 30));
        getContentPane().add(txtasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 170, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Asiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pagina.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquear();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       String id = txtid.getText();
String asiento = txtasi.getText();
String ano = txtaño.getText();
String chapa = txtchapa.getText();
String marca = txtmarca.getText();

if (chapa.isEmpty() || marca.isEmpty()) {
    String mensaje = "Todos los datos son obligatorios!";
    JOptionPane.showMessageDialog(this, mensaje);
    return;
}

if (!editar) {
    cadenaSQL = "INSERT INTO buses VALUES (";
    cadenaSQL += id + ",'";
    cadenaSQL += marca + "','";
    cadenaSQL += chapa + "',";
    cadenaSQL += asiento + ",";
    cadenaSQL += ano + ")";
} else {
    cadenaSQL = "UPDATE buses SET ";
    cadenaSQL += "ano=" + ano + ",";
    cadenaSQL += "chapa='" + chapa + "',";
    cadenaSQL += "asiento=" + asiento + ",";
    cadenaSQL += "marca='" + marca + "'";
    cadenaSQL += " WHERE id=" + id;
}

boolean operacion = controlador.actualizar(cadenaSQL);
System.err.println("Operacion: " + operacion);
inicializar();


    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
       new Menu().setVisible(true);  this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbusquedaKeyReleased

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        txtbusqueda.setText("");
       
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fil=tbluses.getSelectedRow();
        if(fil>=0){
            txtid.setText(tbluses.getValueAt(fil, 0).toString());
            txtmarca.setText(tbluses.getValueAt(fil, 2).toString());
            txtchapa.setText(tbluses.getValueAt(fil, 3).toString());
            
            txtasi.setText(tbluses.getValueAt(fil, 4).toString());
            txtaño.setText(tbluses.getValueAt(fil, 5).toString());
            
            actualizar();
        }
        else{
            JOptionPane.showMessageDialog(null,"No Se A Seleccionado Una Fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
 
        int fila = tbluses.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(this, "Seleccione un registro!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
    return;
}

String id = tbluses.getValueAt(fila, 0).toString();

try {
    cadenaSQL = "SELECT id, marca, chapa, asi, año FROM buses WHERE id = ?";
    // Aquí declaramos e inicializamos el PreparedStatement
    try (PreparedStatement pstmt = controlador.repareStatement(cadenaSQL)) {
        pstmt.setString(1, id);

        resultado = pstmt.executeQuery();

        if (resultado.next()) {
            txtid.setText(resultado.getString("id"));
            txtmarca.setText(resultado.getString("marca"));
            txtchapa.setText(resultado.getString("chapa"));
            txtasi.setText(resultado.getString("asi"));
            txtaño.setText(resultado.getString("año"));

            recuperarBuses();

            editar = true;
        }
    } // El PreparedStatement se cierra automáticamente al salir del bloque try
} catch (SQLException ex) {
    System.err.println("Error al ejecutar la consulta SQL: " + ex);
} finally {
    try {
        // Cierre adecuado de recursos
        if (resultado != null) {
            resultado.close();
        }
    } catch (SQLException ex) {
        System.err.println("Error al cerrar el ResultSet: " + ex);
    }
}

// No está claro dónde deberías desconectar, así que verifica si necesitas esto
// controlador.desconectar();
 
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed
    public void recuperarBuses() {
        String cadenaSQL = "SELECT * FROM buses";
        controlador.cargarJTable((DefaultTableModel) tbluses.getModel(), cadenaSQL);
        tbluses.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbluses.getColumnModel().getColumn(1).setPreferredWidth(350);
        tbluses.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbluses.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbluses.getColumnModel().getColumn(4).setPreferredWidth(100);
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbluses;
    private javax.swing.JTextField txtasi;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtchapa;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmarca;
    // End of variables declaration//GEN-END:variables

   
}
