/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package venta;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Didier Recalde
 */
public class Viajes extends javax.swing.JFrame {

        ResultSet resultado;
    Controlador controlador;
    
    String objeto = "viajes";
    String id = "id";
    String cadenaSQL = null;
    boolean editar = false;
    int estado = 0;
    int gencod = 0;
   
   
    
    public Viajes() {
        initComponents();
        setTitle("Formulario de viajes");
        setLocationRelativeTo(null);
        controlador = new Controlador();
        
        inicializar();
        recuperarViajes();
        limpiar();
        bloquear();
        btnactualizar.setEnabled(false);
        
    }
    
  
 
    

    void limpiar(){
        txthorario.setText("");
        txtdes.setText("");
        txtsalida.setText("");
    }
    public void inicializar() {
        gencod = controlador.generarCodigo(objeto, id);
        txtid.setText(String.valueOf(gencod));
        
        txthorario.setText("0");
        txtdes.setText("1");
        txtsalida.setText("0");
        recuperarViajes();
    }
    
    void bloquear(){
        txthorario.setEnabled(false);
        txtdes.setEnabled(false);
        txtsalida.setEnabled(false);
        btnnuevo.setEnabled(true);
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
    }
    
    void habilitar(){
        txthorario.setEnabled(true);
        txtdes.setEnabled(true);
        txtsalida.setEnabled(true);
        btnnuevo.setEnabled(false);
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
    }
    
    void actualizar(){
        txthorario.setEnabled(true);
        txtdes.setEnabled(true);
        txtsalida.setEnabled(true);
        btnactualizar.setEnabled(true);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txthorario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsalida = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnrmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tviajes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viajes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("horario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 78, -1, -1));

        txthorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorarioActionPerformed(evt);
            }
        });
        getContentPane().add(txthorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 75, 103, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Destino: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 78, -1, -1));
        getContentPane().add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 75, 120, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Salida: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 119, -1, -1));
        getContentPane().add(txtsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 116, 75, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, 76, -1));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 156, 76, -1));

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 156, -1, -1));

        btnrmenu.setText("RMenu");
        btnrmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnrmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 156, 76, -1));

        tviajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "origen", "salida", "destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tviajes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tviajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 524, 154));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 79, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 76, 98, -1));

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 156, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reserva.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
      
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquear();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
          String id = txtid.getText();
        
        
        
        String salida = txtsalida.getText();
        String horario =  txthorario.getText();
        String destino = txtdes.getText();
        
            if (salida.isEmpty() || destino.isEmpty() ) {
            String mensaje = "Todos los datos son obligatorios!";
            JOptionPane.showMessageDialog(this, mensaje);
            return;
        }

        if (!editar) {
            cadenaSQL = "INSERT INTO viajes VALUES (";
            cadenaSQL += id;
            cadenaSQL += ",";
            cadenaSQL += horario;
            cadenaSQL += ",'"; 
            cadenaSQL += salida;
            cadenaSQL += "',";
            cadenaSQL += "'"; 
            cadenaSQL += destino;
            cadenaSQL += "')";
}       else {
            cadenaSQL = "UPDATE viajes SET ";
            cadenaSQL += "horario=" + horario;
            cadenaSQL += ",";
            cadenaSQL += "destino='" + destino + "'"; 
            cadenaSQL += ",";
            cadenaSQL += "salida='" + salida + "'"; 
            cadenaSQL += " WHERE id=" + id;
        }
        
        boolean operacion = controlador.actualizar(cadenaSQL);
        System.err.println("Operacion: " + operacion);
        
        inicializar();
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnrmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrmenuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);  this.dispose();
    }//GEN-LAST:event_btnrmenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fil=tviajes.getSelectedRow();
        if(fil>=0){
            txtid.setText(tviajes.getValueAt(fil, 0).toString());
            txthorario.setText(tviajes.getValueAt(fil, 1).toString());
            txtdes.setText(tviajes.getValueAt(fil, 2).toString());
            txtsalida.setText(tviajes.getValueAt(fil, 3).toString());
            actualizar();
        }
        else{
            JOptionPane.showMessageDialog(null,"No Se A Seleccionado Una Fila");
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
       int fila = tviajes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String id = tviajes.getValueAt(tviajes.getSelectedRow(), 0).toString();
        try {
            cadenaSQL = "SELECT * FROM viajes WHERE id = " + id;
            resultado = controlador.consultar(cadenaSQL);
            if (resultado.next()) {
                txtid.setText(resultado.getString("id"));  // Columna 1
                txtdes.setText(resultado.getString("destino")); // Columna 2
                txthorario.setText(resultado.getString("horario")); // Columna 3
                txtsalida.setText(resultado.getString("salida")); // Columna 4
                txthorario.grabFocus();
                editar = true;
                recuperarViajes();
            }
        } catch (SQLException ex) {
            System.err.println("ERROR SQL EDICION: " + ex);
        } finally {
            controlador.desconectar();
        }
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txthorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorarioActionPerformed
public void recuperarViajes() {
        String cadenaSQL = "SELECT * FROM viajes";
        controlador.cargarJTable((DefaultTableModel) tviajes.getModel(), cadenaSQL);
        tviajes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tviajes.getColumnModel().getColumn(1).setPreferredWidth(350);
        tviajes.getColumnModel().getColumn(2).setPreferredWidth(100);
        tviajes.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnrmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tviajes;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txthorario;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtsalida;
    // End of variables declaration//GEN-END:variables

   
}
